# Generated by Django 3.2 on 2021-04-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upic',
            field=models.ImageField(default='media/upic/default-user.png', null=True, upload_to='upic/'),
        ),
    ]
