# Generated by Django 3.2 on 2021-05-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uname',
        ),
    ]
