# Generated by Django 3.0.3 on 2021-04-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='ptype_serach_index',
            field=models.TextField(blank=True),
        ),
    ]
