# Generated by Django 3.0.3 on 2021-04-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_type_ptype_serach_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='ptype_serach_index',
            new_name='ptype_search_index',
        ),
    ]
