# Generated by Django 3.0.3 on 2021-04-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210406_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='bname_search_index',
            field=models.TextField(blank=True),
        ),
    ]
