# Generated by Django 3.2 on 2021-04-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210428_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='locate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
