# Generated by Django 3.2 on 2021-05-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_brand_locate'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='ptype_color',
            field=models.CharField(default='greenyellow', max_length=50),
        ),
    ]
