# Generated by Django 3.2 on 2021-05-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210528_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locate_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.CharField(default='none', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loctae_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.locate_1')),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='country',
        ),
        migrations.DeleteModel(
            name='Locate',
        ),
        migrations.AddField(
            model_name='brand',
            name='locates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_locate', to='product.loctae_2'),
        ),
    ]
