# Generated by Django 3.2 on 2021-06-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210528_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medium', to='product.brand'),
        ),
    ]
