# Generated by Django 3.2 on 2021-06-21 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_medium_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='brand',
        ),
        migrations.AddField(
            model_name='brand',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.medium'),
        ),
    ]
