# Generated by Django 3.0.3 on 2021-03-31 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('post', '0002_auto_20210329_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='drunk',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drunk_product', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='drunk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drunk_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favb',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_brand', to='product.Brand'),
        ),
        migrations.AlterField(
            model_name='favb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faved_b_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favp',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_product', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='favp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faved_p_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='favp',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_product'),
        ),
        migrations.AddField(
            model_name='postob',
            name='drunk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Drunk'),
        ),
        migrations.AddField(
            model_name='postob',
            name='favp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Favp'),
        ),
    ]
