# Generated by Django 3.0.3 on 2021-04-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210402_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drunk',
            name='day',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='favb',
            name='day',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='favp',
            name='day',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
