# Generated by Django 3.0.3 on 2021-04-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210402_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drunk',
            name='com',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='drunk',
            name='rate',
            field=models.IntegerField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='drunk',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_drunk'),
        ),
        migrations.AddConstraint(
            model_name='favb',
            constraint=models.UniqueConstraint(fields=('brand', 'user'), name='unique_brand'),
        ),
    ]
