# Generated by Django 3.0.3 on 2021-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20210406_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drunk',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
