# Generated by Django 3.0.3 on 2021-04-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210408_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drunk',
            name='rate',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
