# Generated by Django 3.2 on 2021-05-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20210509_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drunk',
            name='rate',
        ),
        migrations.AddField(
            model_name='drunk',
            name='postPic',
            field=models.ImageField(default='noimage.png', upload_to='images/post'),
        ),
    ]
