# Generated by Django 3.2 on 2021-05-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20210523_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='drunk',
            name='rate',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
