# Generated by Django 3.2 on 2021-05-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_drunk_postpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drunk',
            name='postPic',
            field=models.ImageField(blank=True, null=True, upload_to='images/post'),
        ),
    ]
